# Site settings
title: State of the Map LATAM 2017
email: info@osmlatam.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
destination: docs
url: "http://state.osmlatam.org" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
email: "info@osmlatam.org"
facebook_page: "osmlatam"
twitter_username: "osmlatam"
github_username:
website: "http://state.osmlatam.org"
exclude: [README.md]

# Build settings
markdown: kramdown

# Translations
t:
  en:
    language_name: English
    menu:
      about:
        label: About
        url: /en/#about
      venue:
        label: Venue
        url: /en/#venue
      register:
        label: Register
        url: http://osmpe.ourproject.org/inscripcion-inscricao-registration/
      wiki:
        label: Wiki
        url: http://wiki.openstreetmap.org/wiki/State_Of_The_Map_Latam_2017
  es:
    language_name: Español
    menu:
      about:
        label: Sobre
        url: /#about
      venue:
        label: Local
        url: /#venue
      register:
        label: Regístrese
        url: http://osmpe.ourproject.org/inscripcion-inscricao-registration/
      wiki:
        label: Wiki
        url: http://wiki.openstreetmap.org/wiki/Es:State_Of_The_Map_Latam_2017
  pt:
    language_name: Português
    menu:
      about:
        label: Sobre
        url: /pt/#about
      venue:
        label: Local
        url: /pt/#venue
      register:
        label: Inscreva-se
        url: http://osmpe.ourproject.org/inscripcion-inscricao-registration/
      wiki:
        label: Wiki
        url: http://wiki.openstreetmap.org/wiki/Pt:State_Of_The_Map_Latam_2017
